### ISSUE TITLE
unable to enable the module with RNG ^8.1

### ISSUE THREAD

**Issue by novia713** [dpi/rng_date_scheduler#1]
having in my composer.json `"drupal/rng": "^8.1"`
and `"drupal/rng_date_scheduler": "8.1.x-dev"`
i can't enable the date shcheduler,
i guess he can not match the format version number
![seleccion_453](https://cloud.githubusercontent.com/assets/423279/17966907/85334bee-6ac4-11e6-9289-3534821a1d2b.png)

**Comment by dpi** [comment]
I'm on the road at the moment. But I'm pretty sure having a dev version causes issues with version detection. Can you go to an official release? See if that works.

**Comment by novia713** [comment]
hmm, you mean a stable release of rng_date_schedule? the problem is that  i only see dev & RC versions ....
or you mean change my  `minimum-stability` ?
(mine is `"minimum-stability": "dev",`)

the problem is by default my composer installs `^1.1` for `drupal/rng`

anyway, whenever i try to install `rng_date_schedule` i get

```
The requested package drupal/rng_date_scheduler 8.1.0-rc2 exists as drupal/rng_date_scheduler[dev-1.x, 1.x-dev, 1.0.0-rc2, 1.0.0-rc1] but these are rejected by your constraint.
```

**Comment by dpi** [comment]
> having in my composer.json "drupal/rng": "^8.1"
> and "drupal/rng_date_scheduler": "8.1.x-dev"

Please remove the dev channel from rng_date_scheduler.

**Comment by dpi** [comment]
When you get the module it should display its **version number** in the Extend list

![extend](https://cloud.githubusercontent.com/assets/21850/18017057/2d130b86-6c02-11e6-86e6-e006f4095fa3.jpg)

Furthermore, check `rng.info.yml` and `rng_date_scheduler.info.yml` and see what they say for their 'version' line.

**Comment by novia713** [comment]
sir, having `"drupal/rng": "^1.1",` in my composer.json
this is what RNG shows in the modules page
![seleccion_462](https://cloud.githubusercontent.com/assets/423279/18026479/50edb4fc-6c48-11e6-8664-e2aeb7154b0d.png)

its `info.yml` lacks of version number :(

**Comment by dpi** [comment]
I'm not sure what's happening here. I `composer require` the modules in the Drupal root and the resulting files have the correct version info in the yml file. 

Im using https://packagist.drupal-composer.org for the repos

**Comment by novia713** [comment]
weird, i'm using the drupal repo, given the fact drupal-composer is deprecated, besides it still works.
`"url": "https://packages.drupal.org/8"`

i will do a fresh installation and will try again,
i 'll let you know if the problem persists

**Comment by novia713** [comment]
sir, you were right! :)

after a fresh install of drupal-project with composer
all RNG modules works well both with d.o repo and drupal-composer repo

so, i must have something broken on the initial site
(as far as i remenber i also installed that site with the following composer command:)

```
composer create-project  drupal-composer/drupal-project:8.x-dev  secundario.dev  --prefer-dist
```

i suggest to close the issue, i guess it was my bad :/

**Comment by dpi** [comment]
No problem. Perhaps you can compare your composer.json file with the old site. Reporting back may help people in the future. 

Thanks for your time and patience

**Comment by dpi** [comment]
Wrong button

**Comment by novia713** [comment]
i was a while looking for the cause, still not found :-/

the only significative difference between two composer.json is the first one (the one get weid package without version numbers) has this

```
"repositories": {
        "drupal": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    },
```

while the working one, has not the key `drupal` in `repositories`

```
"repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ],
```

maybe because i was changing from one repo to another (drupal-project/d.o) more than 2 or 3 times....
so i really don't understand what happened .... 

perhaps it was a punctual problem with my composer ... i don't really know it
